language: go
before_install:
- pushd $HOME
- wget -q https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.6.zip
- unzip -q go_appengine_sdk_linux_amd64-1.9.6.zip
- cd go_appengine
- ls -la
- export GAE=$(pwd)
- popd
install:
- echo $GAE
- export GOHOME=$GAE
- export PATH=$GAE:$PATH
- which goapp
- goapp env
- mkdir -p $HOME/gopath/src/github.com/gin-gonic
- cd $HOME/gopath/src/github.com/gin-gonic
- git clone https://github.com/gin-gonic/gin.git
- cd $HOME/gopath/src/github.com/gin-gonic/gin
- git checkout app_engine
- goapp get ./...
- goapp install
- cd $TRAVIS_BUILD_DIR
script:
- goapp get ./...
- goapp test -v ./...
