language: go
before_install:
- pushd $HOME
- wget -q https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.18.zip
- unzip -q go_appengine_sdk_linux_amd64-1.9.18.zip
- cd go_appengine
- ls -la
- export GAE=$(pwd)
- popd
install:
- echo $GAE
- export GOHOME=$GAE
- export PATH=$GAE:$PATH
- which goapp
- goapp env
- mkdir -p $HOME/gopath/src/github.com/gin-gonic
- cd $HOME/gopath/src/github.com/gin-gonic
- git clone https://github.com/gin-gonic/gin.git
- cd $HOME/gopath/src/github.com/gin-gonic/gin
- git checkout app_engine
- goapp get ./...
- goapp install
- cd $TRAVIS_BUILD_DIR
- goapp get -t github.com/smartystreets/goconvey
- goapp get github.com/axw/gocov/gocov
- goapp get code.google.com/p/go.tools/cmd/cover
- goapp get github.com/mattn/goveralls
script:
- goapp get ./...
- goapp test -v -covermode=count -coverprofile=profile.cov ./...
- $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN -coverprofile=profile.cov
env:
  global:
    secure: G8J/VkWjqk1LFJzgfOgIuEAcLztNL4f8W8m3V3oX4AD7td/RhjbRYGyNDPAiQcVDkPOr6+RUIi19el+QlGDv1zgUqA2Lb8YJTNYuIzzGr5QOuu9FWyXPY7AlUsnIUh46JIT6mJvuqWWzUoF/9d/PFGCljhfjtwZ1YCxK/1OrgAQ=
